# -*- coding: utf-8 -*-
"""Untitled58.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IxKijd622r79UngDkwkorpY6LkEGGli_
"""

import matplotlib.pyplot as plt
import numpy as np

def Douglas(num_step, tstep, YGROSS_0):
     
     mu = 0.05
     sigma = 0.01
     tstep = 0.01
     N = round(num_step/tstep)
     t = np.linspace(0, num_step, N)
     W = np.random.standard_normal(size = N) 
     W = np.cumsum(W)*np.sqrt(tstep) ### standard brownian motion ###
     X = (mu-0.5*sigma**2)*t + sigma*W 
     Y= YGROSS_0*np.exp(X) ### geometric brownian motion ###
     return Y
     #plt.plot(t, YGROSS)
     #plt.show()
